# handlers file for postfix
---
- name: New aliases
  ansible.builtin.command: newaliases
# - name: new virtual aliases
#   ansible.builtin.command: postmap hash:/etc/postfix/virtual
# - name: postmap sasl_passwd
#   ansible.builtin.command: postmap hash:/etc/postfix/sasl_passwd
# - name: postmap sender_canonical_maps
#   ansible.builtin.command: postmap hash:/etc/postfix/sender_canonical_maps
# - name: postmap generic
#   ansible.builtin.command: postmap hash:/etc/postfix/generic
- name: Restart postfix
  ansible.builtin.command: /bin/true
  notify:
    - Restart service
- name: Restart service
  ansible.builtin.service:
    name: postfix
    state: restarted
  when: service_default_state | default('started') == 'started'
