---
# tasks file for upgrade-dist
- name: Debian upgrade
  include_tasks: debian.yml
  when: ansible_distribution == 'Debian'
  tags: package
- name: Ubuntu upgrade
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: package
