---
- name: upgrade system
  apt:
    upgrade: dist
    state: present
    update_cache: yes

- name: remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: remove useless packages from the cache
  apt:
    autoclean: yes
