---
- name: Configure acme.sh
  hosts: all
#  remote_user: root
  vars_prompt:
    - name: "USER"
      prompt: "Enter user name"
      private: "no"
      default: "runner"
    - name: "FQDN"
      prompt: "Domain name"
      private: "no"
      default: "blossapp.com"
  roles:
    - { role: upgrade-dist, tags: update }
    - { role: acme.sh, tags: cert }
