---
- name: Add ssh key
  hosts: all
  gather_facts: false
  tasks:
  - name: Set authorized key for root
    ansible.posix.authorized_key:
      user: root
      state: present
      key: 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBADGeH0MkZIVwnbDT+Wi/qAVrpUCkX1JLk20EYPbN+DCTls/zECG0mNsJ96ywbE6FAlq0q5THtXwSwzqG21V/2g3kABBRLy7V6A8DQb+W+8rDmHow568WPZdgaBc8lCc4s2CPjjNIGJxD0y+l+p7MtwJVTaU63kK1rojWzAm3LTwNQ8c7Q== ok'
