---
- hosts: all
  gather_facts: false
  tasks:
  - name: resize to up buffer
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      sysctl_file: /etc/sysctl.d/11-buffer.conf
      sysctl_set: yes
      state: present
      reload: yes
    loop:
      - { name: 'net.core.wmem_default', value: '524288' }
      - { name: 'net.core.rmem_default', value: '524288' }

