---
- name: Setup and configure dm-crypt
  hosts: all
  remote_user: root
  vars_prompt:
    - name: "CRYPT_SIZE"
      prompt: "Enter size of container in GiB"
      private: false
    - name: "CRYPT_PASSWD"
      prompt: "Enter password"
      private: false
  roles:
    - { role: utc, tags: ntp }
    - { role: disable-ipv6, tags: sysctl }
    - { role: crypt, tags: security }
