---
- hosts: all
  gather_facts: false
  tasks:
  - name: disable IPv6
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      sysctl_file: /etc/sysctl.d/10-dis_ipv6.conf
      sysctl_set: yes
      state: present
      reload: yes
    loop:
      - { name: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
      - { name: 'net.ipv6.conf.default.disable_ipv6', value: '1' }

