---
- name: Setup and configure Postfix server
  hosts: all
  remote_user: root
  vars_prompt:
    - name: "FQDN"
      prompt: 'Domain name:'
      private: false
  roles:
    - { role: upgrade-dist, tags: update }
    - { role: postfix, tags: mta }
