---
- hosts: all
  vars_prompt:
  - name: "USER"
    prompt: "Enter user name"
    private: no
    default: ubuntu
  - name: "FQDN"
    prompt: 'Domain name'
    private: no
    default: rancher.com
  roles:
    - { role: upgrade-dist, tags: update }
    - { role: rancher, tags: setup }
