---
- hosts: all
  remote_user: root
  vars_prompt:
  - name: "PW_ROOT"
    prompt: "Enter root passwd"
    encrypt: "sha512_crypt"
    confirm: yes
    private: no
  - name: "SOCKS_PORT"
    prompt: "Enter port"
    private: no
    default: 53535
  roles:
    - { role: sockd, tags: sockd }
