---
- include_tasks: time_settings.yml
- include_tasks: disable_ipv6.yml
- hosts: all
  remote_user: root
  vars_prompt:
  - name: "pwroot"
    prompt: "Enter root passwd"
    encrypt: "sha512_crypt"
    confirm: yes
    salt_size: 7
    private: no
  - name: "hostname"
    prompt: "Enter hostname for node"
    private: no
  - name: "server_env"
    prompt: "use a single value main or reserv"
    private: no
    default: "main"
  - name: "contsize"
    prompt: "Enter size of container in GiB"
    private: no
    default: "5"
  - name: "passcont"
    prompt: "Enter passcont, use: openssl rand -base64 48"
    private: no
  roles:
    - { role: upgrade-dist, tags: update }
    - { role: voip, tags: pbx }
