---
- name: Install and configure wordpress
  hosts: all
#  remote_user: root
  vars_prompt:
    - name: "USER"
      prompt: "Enter user name"
      private: false
      default: "ubuntu"
    - name: "mysql"
      prompt: "Do you need install MySQL server?"
      private: false
      default: "no"
  roles:
    - { role: root-config, tags: config }
    - { role: upgrade-dist, tags: config }
    - { role: wordpress, tags: wordpress }
    - { role: motd, tags: config }
