---
- name: Prepare instance
  ansible.legacy.include_tasks: ubuntu.yml
  tags: configure
- name: MySQL config
  ansible.legacy.include_tasks: mysql.yml
  tags: mysql
  when: mysql is defined and mysql == "yes"
- name: WP salt config
  ansible.legacy.include_tasks: wp_config.yml
  tags: wp
