---
- name: Install mysql server
  ansible.builtin.apt:
    pkg: ['mysql-server', 'libmysqlclient-dev', 'python3-pymysql']
    state: latest
    install_recommends: false
    update_cache: 'True'
- name: Create a wp database "{{ inventory_hostname }}"
  community.mysql.mysql_db:
    name: wordpress
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
- name: Create wp user
  community.mysql.mysql_user:
    login_unix_socket: /run/mysqld/mysqld.sock
    state: present
    name: wpuser
    password: 'Ln0ZuGHG+6BWIZQId2lTxiWhcPtSsueC'
    priv:
      'wordpress.*': 'ALL,GRANT'
