# tasks file for postfix
---
- name: configure debconf
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ postfix_debconf_selections }}"
  tags:
    - configuration
    - postfix
    - postfix-install

- name: install package
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ postfix_install }}"
  tags:
    - configuration
    - postfix
    - postfix-install

- name: update configuration file main.cf
  template:
    src: main_cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags:
    - configuration
    - postfix
    - postfix-configuration

- name: upload header_checks
  template:
    src: header_checks.j2
    dest: /etc/postfix/header_checks
    mode: 0600

- name: configure aliases
  lineinfile:
    dest: /etc/aliases
    regexp: '^{{ item.user }}:.*'
    line: '{{ item.user }}: {{ item.alias }}'
    owner: root
    group: root
    mode: 0644
    create: true
    state: present
  with_items: "{{ postfix_aliases }}"
  notify:
    - new aliases
    - restart postfix
  tags:
    - configuration
    - postfix
    - postfix-aliases

- name: create cert dir
  file:
    path: /etc/nginx/certs/
    state: directory
    mode: 0750

- name: create Diffie-Helman key
  openssl_dhparam:
    path: /etc/nginx/certs/dhparam.pem
    size: 2048

- name: transport
  template:
    src: transport.j2
    dest: /etc/postfix/transport
    mode: 0600

- name: postmap for transport
  command: |
    postmap /etc/postfix/transport
  args:
    chdir: /etc/postfix/
    removes: /etc/postfix/transport

- name: start service
  service:
    name: postfix
    state: started

#    state: "{{ service_default_state | default('started') }}"
#    enabled: "{{ service_default_enabled | default(true) | bool }}"
#  tags:
#    - configuration
#    - postfix
#    - postfix-start-enable-service
