# tasks file for postfix
---
- name: Configure debconf
  ansible.builtin.debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ postfix_debconf_selections }}"
  tags:
    - configuration
    - postfix
    - postfix-install
- name: Install package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ postfix_install }}"
  tags:
    - configuration
    - postfix
    - postfix-install
- name: Update configuration file main.cf
  ansible.builtin.template:
    src: main_cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  notify: Restart postfix
  tags:
    - configuration
    - postfix
    - postfix-configuration
- name: Upload header_checks
  ansible.builtin.template:
    src: header_checks.j2
    dest: /etc/postfix/header_checks
    mode: '0600'
- name: Configure aliases
  ansible.builtin.lineinfile:
    dest: /etc/aliases
    regexp: '^{{ item.user }}:.*'
    line: '{{ item.user }}: {{ item.alias }}'
    owner: root
    group: root
    mode: '0644'
    create: true
    state: present
  with_items: "{{ postfix_aliases }}"
  notify:
    - New aliases
    - Restart postfix
  tags:
    - configuration
    - postfix
    - postfix-aliases
- name: Create cert dir
  ansible.builtin.file:
    path: /etc/nginx/certs/
    state: directory
    mode: '0750'
- name: Create Diffie-Helman key
  community.crypto.openssl_dhparam:
    path: /etc/nginx/certs/dhparam.pem
    size: '2048'
- name: Transport
  ansible.builtin.template:
    src: transport.j2
    dest: /etc/postfix/transport
    mode: '0600'
- name: Postmap for transport
  ansible.builtin.command: |
    postmap /etc/postfix/transport
  args:
    chdir: /etc/postfix/
    removes: /etc/postfix/transport
- name: Start service
  ansible.builtin.service:
    name: postfix
    state: started
#    state: "{{ service_default_state | default('started') }}"
#    enabled: "{{ service_default_enabled | default(true) | bool }}"
#  tags:
#    - configuration
#    - postfix
#    - postfix-start-enable-service
