---
- name: install packages
  apt:
    pkg: ['bash-completion', 'screen', 'vim']
    state: latest
    update_cache: true

- name: purge vim-tiny
  apt:
    pkg: vim-tiny
    state: absent
    autoremove: yes
  when: ansible_distribution_major_version|int >= 10

- name: update bashrc
  template:
    src: bashrc.j2
    dest: /root/.bashrc
    mode: 0644
    backup: yes

- name: create vimrc
  template:
    src: vimrc.j2
    dest: /root/.vimrc
    mode: 0644
    backup: yes

- name: create screenrc
  template:
    src: screenrc.j2
    dest: /root/.screenrc
    mode: 0644
    backup: yes

