---
- name: Upgrade system
  ansible.builtin.apt:
    upgrade: dist
    state: present
    update_cache: true

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true

- name: Install packages
  ansible.builtin.apt:
    name: ['ca-certificates', 'easy-rsa', 'nftables', 'openssl', 'openvpn', 'sshguard']
    state: latest
    install_recommends: false

- name: Create udp config
  ansible.builtin.template:
    src: udp.j2
    dest: /etc/openvpn/server/udp.conf
    mode: '0644'
    backup: true

- name: Create firewall config
  ansible.builtin.template:
    src: nft.j2
    dest: /etc/nftables.conf
    mode: '0755'
    backup: true
  notify:
    - Reload firewall
