---
- name: Stretch configure (upgrade if stretch)
  block:
    - name: Delete backports.list
      ansible.builtin.file:
        state: absent
        path: /etc/apt/sources.list.d/backports.list
    - name: Up distr to stretch
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: 'stretch'
        replace: 'buster'
    - name: Upgrade system
      ansible.builtin.apt:
        upgrade: dist
        state: present
        update_cache: true
        dpkg_options: 'force-confold,force-confdef'
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true
    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: true
    - name: Reboot the node
      ansible.builtin.reboot:
        reboot_timeout: 3600
  when: ansible_distribution_release == 'stretch'
- name: Buster configure (upgrade if buster)
  block:
    - name: Delete backports.list
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/backports.list
        state: absent
    - name: Upgrade buster
      ansible.builtin.template:
        src: sources.list.j2
        dest: /etc/apt/sources.list
        mode: 0644
    - name: Upgrade buster to bullseye
      ansible.builtin.apt:
        upgrade: dist
        state: present
        update_cache: true
        dpkg_options: 'force-confold,force-confdef'
    - name: Remove dependencies that are no longer required buster
      ansible.builtin.apt:
        autoremove: true
    - name: Remove useless packages from the cache buster
      ansible.builtin.apt:
        autoclean: true
    - name: Reboot the node
      ansible.builtin.reboot:
        reboot_timeout: 3600
  when: ansible_distribution_release == 'buster'
