---
- name: Reload asterisk
  ansible.builtin.service:
    name: asterisk
    state: reloaded
- name: Purge iptables
  ansible.builtin.apt:
    pkg: iptables
    state: absent
  when: nftables is succeeded
