---
# MySQL install Version 1.01

- block:
  - name: Determine required MySQL Python libraries.
    set_fact:
      mysql_python_package_debian: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-mysqldb{% else %}python-mysqldb{% endif %}"
    when: mysql_python_package_debian is not defined
  - name: add mysql key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 467B942D3A79BD29
      keyring: /etc/apt/trusted.gpg.d/mysql.gpg
  - name: add repo mysql-community
    apt_repository:
      repo: deb https://repo.mysql.com/apt/debian/ {{ ansible_distribution_release }} mysql-5.7
      state: present
      filename: mysql
  - name: ensure MySQL python libraries are installed.
    apt:
      name: "{{ mysql_python_package_debian }}"
      state: present
  - name: install mysql packages
    apt:
      pkg: ['mysql-server', 'mysql-client']
      state: present
      dpkg_options: 'force-confold,force-confdef'
      install_recommends: no
  - block:
    - name: add config if not exist
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/mysqld.cnf
        regexp: '\[mysqld\]'
        line: '[mysqld]'
        mode: '0644'
        create: yes
    - name: innodb_file_per_table
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/mysqld.cnf
        regexp: 'innodb_file_per_table'
        line: innodb_file_per_table = 1
    - name: apply innodb changes
      service:
        name: mysql
        state: restarted
        enabled: yes
  - name: removes all anonymous user accounts
    mysql_user:
      name: ''
      host_all: yes
      state: absent
  tags: mysql
