---
- name: Purge iptables
  ansible.builtin.apt:
    pkg: iptables
    state: absent
  when: nftables is succeeded
- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: root_prohibit_password is succeeded
