---
- name: Create container file
  block:
    - name: Create cont file
      ansible.builtin.command:
        "{{ item }}"
      with_items:
        - truncate -s '{{ contsize }}'G /data.img
        - fallocate -n -l '{{ contsize }}'GiB /data.img
  rescue:
    - name: Create cont file
      ansible.builtin.command: fallocate -l '{{ contsize }}'GiB /data.img
- name: Add loop module
  community.general.modprobe:
    name: loop
    state: present
- name: Attach loop device
  ansible.builtin.command:
    losetup -f /data.img
- name: Install cryptsetup package
  ansible.builtin.apt:
    pkg: cryptsetup
    state: present
    install_recommends: no
    update_cache: true
- name: Create errata countainer
  luks_device:
    device: "/dev/loop0"
    state: "opened"
    type: luks1
    cipher: 'aes-xts-plain64'
    hash: "sha256"
    name: "data"
    passphrase: "{{ passcont }}"
- name: Add ext4 module
  community.general.modprobe:
    name: ext4
    state: present
  register: ext4
  ignore_errors: true
- name: Create FS ext4
  filesystem:
    fstype: ext4
    dev: /dev/mapper/data
  when: ext4 is succeeded
- name: Create FS ext3
  filesystem:
    fstype: ext3
    dev: /dev/mapper/data
  when: ext4 is failed
- name: Add dm-mod module
  community.general.modprobe:
    name: dm-mod
    state: present
- name: Create errata dir
  ansible.builtin.file:
    path: '/errata/'
    state: directory
    mode: 0755
- name: Mount errata
  mount:
    name: /errata
    src: /dev/mapper/data
    opts: "noauto,noatime,nodiratime"
    state: mounted
    fstype: ext4
- name: Create dirs
  ansible.builtin.file:
    path: '/errata/{{ item }}'
    state: directory
    mode: 0755
    recurse: yes
  with_items:
    - var/log/asterisk
    - etc/asterisk
- name: Link configs to errata
  ansible.builtin.file:
    src: '/errata/etc/{{ item }}'
    dest: '/etc/{{ item }}'
    state: link
    force: yes
  with_items:
    - asterisk
- name: Link configs
  ansible.builtin.file:
    src: /errata/var/{{ item.from }}
    dest: /var/{{ item.path }}
    state: link
    force: yes
  with_items:
    - { from: log/asterisk, path: log/asterisk }
