---
- import_tasks: crypt.yaml
- name: set hostname
  hostname:
    name: "{{ hostname }}"
  ignore_errors: True
- name: add hostname in hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.1.1\t{{ hostname }}"
- name: set root passwd
  user:
    name: root
    shell: /bin/bash
    password: "{{ pwroot }}"
    generate_ssh_key: yes
    state: present
- name: change /etc/apt/sources.list
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
- name: install packages
  apt:
    pkg: ['cryptsetup', 'asterisk']
    state: present
    install_recommends: no
    update_cache: true
- name: add ~/.bashrc
  template:
    src: bashrc_root.j2
    dest: /root/.bashrc
    mode: 0600
- name: add ~/.vimrc
  template:
    src: vimrc.j2
    dest: /root/.vimrc
    mode: 0600
- name: add pub key
  template:
    src: pub.j2
    dest: /root/.ssh/authorized_keys
- name: disable history
  lineinfile:
    dest: /root/.profile
    line: "unset HISTFILE"
    insertbefore: "mesg n"
- name: del history
  file:
    path: /root/.bash_history
    state: absent
  ignore_errors: True
- name: packages purge
  apt:
    pkg: ['exim4-config', 'portmap', 'rpcbind', 'apache2', 'postfix', 'cups', 'unbound', 'dovecot-core', 'dovecot-imapd', 'dovecot-pop3d', 'spamassassin', 'samba', 'vsftpd', 'mysql-server']
    state: absent
    autoremove: yes
- name: disable autostart on boot
  systemd:
    enabled: no
    name: asterisk
    state: stopped
    masked: no
- name: set iax.conf
  template:
    src: iax.j2
    dest: /etc/asterisk/iax.conf
    mode: 0640
    backup: yes
    owner: asterisk
    group: asterisk
- name: set sip.conf
  template:
    src: sip.j2
    dest: /etc/asterisk/sip.conf
    mode: 0640
    backup: yes
    owner: asterisk
    group: asterisk
- name: disable cdr_radius
  lineinfile:
    dest: /etc/asterisk/modules.conf
    line: 'noload => cdr_radius.so'
    regexp: '^noload => cdr_radius\.so'
    insertafter: 'autoload='
- name: set extensions.conf
  template:
    src: extensions.j2
    dest: /etc/asterisk/extensions.conf
    mode: 0640
    backup: yes
    owner: asterisk
    group: asterisk
- name: set extensions.ael
  template:
    src: extensions_ael.j2
    dest: /etc/asterisk/extensions.ael
    mode: 0640
    backup: yes
    owner: asterisk
    group: asterisk
  notify:
    - reload asterisk
- name: nrpe_local.conf
  template:
    src: nrpe_voip.j2
    dest: /etc/nagios/nrpe_local.cfg
  notify:
    - reload nagios-nrpe-server
- block:
  - name: install rsyslog
    apt:
      pkg: rsyslog
      state: present
      install_recommends: no
  - name: create conf rsyslog
    blockinfile:
      path: /etc/rsyslog.conf
      backup: yes
      insertafter: "WorkDirectory"
      marker: "# {mark} Fixes for ram"
      block: |
        $QueueType Disk
        $QueueMaxFileSize 1m
    notify:
      - reload rsyslog
- name: interfaces
  debug:
    msg: address is {{ ansible_default_ipv4.address }}
- block:
  - name: install openvpn package
    apt:
      name: openvpn
      state: present
      install_recommends: no
  - name: create certs directory
    file:
      path: /etc/openvpn/certs
      state: directory
      mode: '0755'
  - name: update owner of directory
    file:
      path: /errata/var/log/asterisk
      state: directory
      mode: '0755'
      owner: asterisk
      group: asterisk
  - name: create directories on main server
    file:
      path: /etc/systemd/system/openvpn@client_udp.service.d
      state: directory
      mode: '0755'
    when: server_env is defined and server_env == "main"
  - name: create override.conf on main server
    template:
      src: ovpn_voip_override.j2
      dest: /etc/systemd/system/openvpn@client_udp.service.d/override.conf
    when: server_env is defined and server_env == "main"
  - name: create openvpn config on main server
    template:
      src: ovpn_udp.j2
      dest: /etc/openvpn/client_udp.conf
    when: server_env is defined and server_env == "main"
  - name: create directories on reserv server
    file:
      path: /etc/systemd/system/openvpn@client_tcp.service.d
      state: directory
      mode: '0755'
    when: server_env is defined and server_env == "reserv"
  - name: create override.conf on reserv server
    template:
      src: ovpn_voip_override.j2
      dest: /etc/systemd/system/openvpn@client_tcp.service.d/override.conf
    when: server_env is defined and server_env == "reserv"
  - name: create openvpn config on reserv server
    template:
      src: ovpn_tcp.j2
      dest: /etc/openvpn/client_tcp.conf
    when: server_env is defined and server_env == "reserv"
  - name: configure nrpe
    include: nrpe.yml
    tags: nrpe
  - name: configure firewall
    include: firewall.yml
    tags: firewall
  - name: add cron tasks
    include: cron.yml
    tags: cron
