---
- name: install monitoring plugins
  apt:
    name: monitoring-plugins-basic

- name: add plugin check_registrations
  template:
    src: check_registrations.j2
    dest: /usr/lib/nagios/plugins/check_registrations
    mode: 0755

- name: add plugin check_trunks
  template:
    src: check_trunks.j2
    dest: /usr/lib/nagios/plugins/check_trunks
    mode: 0755

- name: add check_trunks command to nrpe config
  lineinfile:
    dest: /etc/nagios/nrpe_local.cfg
    line: "command[check_trunks]=sudo /usr/lib/nagios/plugins/check_trunks"
    state: present
    regexp: '^command\[check_trunks\]='
  notify:
    - reload nrpe

- name: add check_registrations command to nrpe config
  lineinfile:
    dest: /etc/nagios/nrpe_local.cfg
    line: "command[check_registrations]=sudo /usr/lib/nagios/plugins/check_registrations"
    state: present
    regexp: '^command\[check_registrations\]='
  notify:
    - reload nrpe

- name: add check_memory command to nrpe config
  lineinfile:
    dest: /etc/nagios/nrpe_local.cfg
    line: "command[check_memory]=/usr/lib/nagios/plugins/check_memory -f -w 10 -c 5"
    state: present
    regexp: '^command\[check_memory\]='
  notify:
    - reload nrpe

- name: install plugin for sip and iax
  get_url:
    dest: /usr/lib/nagios/plugins/check_asterisk_peers
    url: 'https://exchange.nagios.org/components/com_mtree/attachment.php?link_id=1304&cf_id=29'
    mode: 0755

- name: install plugin for sip and iax
  get_url:
    dest: /usr/lib/nagios/plugins/check_memory
    url: 'https://raw.githubusercontent.com/justintime/nagios-plugins/master/check_mem/check_mem.pl'
    mode: 0755

- name: add check_asterisk_peers to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: '^root'
    regexp: '^nagios ALL=\(ALL\) NOPASSWD: /usr/lib/nagios/plugins/check_asterisk_peers'
    line: 'nagios ALL=(ALL) NOPASSWD: /usr/lib/nagios/plugins/check_asterisk_peers'
    validate: 'visudo -cf %s'

- name: add check_registrations to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: '^root'
    regexp: '^nagios ALL=\(ALL\) NOPASSWD: /usr/lib/nagios/plugins/check_registrations'
    line: 'nagios ALL=(ALL) NOPASSWD: /usr/lib/nagios/plugins/check_registrations'
    validate: 'visudo -cf %s'

- name: add check_trunks to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: '^root'
    regexp: '^nagios ALL=\(ALL\) NOPASSWD: /usr/lib/nagios/plugins/check_trunks'
    line: 'nagios ALL=(ALL) NOPASSWD: /usr/lib/nagios/plugins/check_trunks'
    validate: 'visudo -cf %s'
