---
- name: Install packages
  ansible.builtin.apt:
    pkg: bind9
    state: present
    update_cache: true
  tags: pkgs
- name: Create dirs
  ansible.builtin.file:
    path: '/{{ item }}'
    state: directory
    mode: "0755"
    owner: bind
    group: bind
    recurse: true
  with_items:
    - var/log/dns
    - var/cache/bind
- name: Include master.conf
  ansible.builtin.lineinfile:
    path: /etc/bind/named.conf.local
    state: present
    regexp: '^include'
    line: 'include "master.conf";'
    owner: bind
    group: bind
    backup: true
  tags: dns
- name: Modify named.conf.options
  ansible.builtin.template:
    src: bind.options.j2
    dest: /etc/bind/named.conf.options
    mode: "0660"
    owner: bind
    group: bind
    backup: true
  tags: dns
- name: Create named.conf.log
  ansible.builtin.template:
    src: bind.log.j2
    dest: /etc/bind/named.conf.log
    mode: "0660"
    owner: bind
    group: bind
    backup: true
  tags: dns
- name: Include named.conf.log
  ansible.builtin.lineinfile:
    path: /etc/bind/named.conf
    state: present
    line: 'include "/etc/bind/named.conf.log";'
    backup: true
  tags: dns
- name: Bind owner and group to query.log
  ansible.builtin.file:
    owner: bind
    group: bind
    path: '{{ item }}'
    mode: "0755"
    state: touch
  with_items:
    - /etc/bind
  tags: dns
- name: Bind owner and group to query.log
  ansible.builtin.file:
    owner: bind
    group: bind
    path: '/var/log/dns/query.log'
    mode: "0644"
    state: touch
  tags: dns
- name: Create file zone
  ansible.builtin.lineinfile:
    path: /var/cache/bind/master.conf
    line: "zone \"{{ FQDN }}\" { type master; file \"{{ FQDN }}.zone\"; };"
    create: true
    group: bind
    mode: "0644"
    backup: true
  tags: dns
- name: Create config {{ FQDN }}
  ansible.builtin.template:
    src: dom.j2
    dest: "/var/cache/bind/{{ FQDN }}.zone"
    group: bind
    mode: "0644"
    backup: true
  notify:
    - Reload bind
  tags: dns
