---
- name: install packages
  apt:
    pkg: bind9
    state: present
    update_cache: true
  tags: pkgs

- name: create dirs
  file:
    path: '/{{ item }}'
    state: directory
    mode: 0755
    owner: bind
    group: bind
    recurse: yes
  with_items:
    - var/log/dns
    - var/cache/bind

- name: include master.conf
  lineinfile:
    path: /etc/bind/named.conf.local
    state: present
    regexp: '^include'
    line: 'include "master.conf";'
    owner: bind
    group: bind
    backup: yes
  tags: dns

- name: modify named.conf.options
  template:
    src: bind.options.j2
    dest: /etc/bind/named.conf.options
    mode: 0660
    owner: bind
    group: bind
    backup: yes
  tags: dns

- name: create named.conf.log
  template:
    src: bind.log.j2
    dest: /etc/bind/named.conf.log
    mode: 0660
    owner: bind
    group: bind
    backup: yes
  tags: dns

- name: include named.conf.log
  lineinfile:
    path: /etc/bind/named.conf
    state: present
    line: 'include "/etc/bind/named.conf.log";'
    backup: yes
  tags: dns

- name: bind owner and group to query.log
  file:
    owner: bind
    group: bind
    path: '{{ item }}'
    mode: 0755
    state: touch
  with_items:
    - /etc/bind
  tags: dns

- name: bind owner and group to query.log
  file:
    owner: bind
    group: bind
    path: '/var/log/dns/query.log'
    mode: 0644
    state: touch
  tags: dns

- name: create file zone
  lineinfile:
    path: /var/cache/bind/master.conf
    line: "zone \"{{ FQDN }}\" { type master; file \"{{ FQDN }}.zone\"; };"
    create: yes
    group: bind
    mode: 0644
    backup: yes
  tags: dns

- name: create {{ FQDN }} config
  template:
    src: dom.j2
    dest: "/var/cache/bind/{{ FQDN }}.zone"
    group: bind
    mode: 0644
    backup: yes
  notify:
    - reload bind
  tags: dns

### DNS ####
