name: Ansible Lint
on:
  push:
    branches-ignore:
      - dev
  pull_request:
    branches:
      - dev
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install dependencies including ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: ansible-lint
        run: |
          for i in $(ls *.yml);do echo -e "\n\t$i";ansible-lint $i;done
