name: Ansible Lint Development
on:
  push:
    branch: [dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: install dependencies including ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: linter launch
        run: |
          for i in $(ls *.yml);do echo -e "\n\t$i";ansible-lint $i;done
